// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 123 $
// $Date: 2010-3-31 $
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("IDPickerReport")]
[assembly: AssemblyDescription("Command-line interface for generates HTML, text, and/or XML output from an IDPicker analysis.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("IDPicker")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2010")]
[assembly: AssemblyVersion("2.6.123")]
[assembly: AssemblyFileVersion("2.6.123")]
