// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 234 $
// $Date: 2010-11-10 $
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Common")]
[assembly: AssemblyDescription("Implements IDPicker's shared logic.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("IDPicker")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2010")]
[assembly: AssemblyVersion("2.6.234")]
[assembly: AssemblyFileVersion("2.6.234")]
