// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 108 $
// $Date: 2010-2-2 $
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Presentation")]
[assembly: AssemblyDescription("Implements IDPicker's presentation logic.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("IDPicker")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2010")]
[assembly: AssemblyVersion("2.6.108")]
[assembly: AssemblyFileVersion("2.6.108")]
