// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 221 $
// $Date: 2010-11-4 $
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("IDPicker.Util")]
[assembly: AssemblyDescription("IDPicker utilities.")]
[assembly: AssemblyCompany("Vanderbilt University")]
[assembly: AssemblyProduct("IDPicker")]
[assembly: AssemblyCopyright("Copyright © Vanderbilt University 2010")]
[assembly: AssemblyVersion("3.0.221")]
[assembly: AssemblyFileVersion("3.0.221")]
